name: Lophine CI

on:
  pull_request:

  workflow_dispatch:
    inputs:
      force-release:
        description: "Force disable release if you enter false, force release if you enter true, default release if not released else skip release"
        required: false
        default: ""

      force-push:
        description: "Force disable push to repo if you enter false, force push to repo if you enter true, default push if not released else skip push repo"
        required: false
        default: ""

      comments:
        description: "Add comments to release"
        required: false
        default: ""

permissions: write-all

jobs:
  build:
    runs-on: namespace-profile-bacteriawa
    environment: default

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout Git Repository
        uses: namespacelabs/nscloud-checkout-action@v8
        with:
          fetch-depth: 0
          dissociate: true

      - name: Setup Namespace Gradle Cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle

      - name: Set Up JDK
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 25

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure Git User Details
        run: |
          git config --global user.email "ci@lophinelabs.com"
          git config --global user.name "LophinelabsCI"

      - name: Apply All Patches
        run: ./gradlew --refresh-dependencies applyAllPatches

      - name: Build Paperclip Jar
        run: ./gradlew --refresh-dependencies createPaperclipJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.project_id_b }} CI Artifacts
          path: lophine-server/build/libs/*-paperclip-*.jar

      - name: Publish To Repo
        continue-on-error: true
        run: ./gradlew --refresh-dependencies generateDevelopmentBundle publish -PpublishDevBundle=true
        env:
          PRIVATE_MAVEN_REPO_PASSWORD: ${{ secrets.PRIVATE_MAVEN_REPO_PASSWORD }}
          PRIVATE_MAVEN_REPO_USERNAME: ${{ secrets.PRIVATE_MAVEN_REPO_USERNAME }}
