name: Lophine CI

on:
  pull_request:

  workflow_dispatch:
    inputs:
      force-release:
        description: "Force disable release if you enter false, force release if you enter true, default release if not released else skip release"
        required: false
        default: ""

      force-push:
        description: "Force disable push to repo if you enter false, force push to repo if you enter true, default push if not released else skip push repo"
        required: false
        default: ""

      comments:
        description: "Add comments to release"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: lophine-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: namespace-profile-bacteriawa
    environment: default

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout Git Repository
        uses: namespacelabs/nscloud-checkout-action@v9
        with:
          fetch-depth: 0

      - name: Set Up JDK
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: 25
          cache: ""

      - name: Set Up Namespace Gradle Cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle

      - name: Set Up Namespace Gradle Build Cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Configure Git User Details
        run: |
          git config --global user.email "ci@lophinelabs.com"
          git config --global user.name "LophinelabsCI"

      - name: Apply All Patches
        run: |
          ./gradlew \
            --init-script=/tmp/init.gradle \
            applyAllPatches \
            --stacktrace

      - name: Build Paperclip Jar
        run: |
          ./gradlew \
            --init-script=/tmp/init.gradle \
            createPaperclipJar \
            --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Lophine CI Artifacts
          path: lophine-server/build/libs/*-paperclip-*.jar
          if-no-files-found: error

      - name: Publish To Repo
        if: github.event_name == 'workflow_dispatch'
        continue-on-error: true
        run: |
          ./gradlew \
            --init-script=/tmp/init.gradle \
            generateDevelopmentBundle \
            publish \
            -PpublishDevBundle=true \
            --stacktrace
        env:
          PRIVATE_MAVEN_REPO_PASSWORD: ${{ secrets.PRIVATE_MAVEN_REPO_PASSWORD }}
          PRIVATE_MAVEN_REPO_USERNAME: ${{ secrets.PRIVATE_MAVEN_REPO_USERNAME }}
